apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - virtualservice.yaml
  - authorizationpolicy.yaml
patches:
  - path: base-path-patch.yaml
  - path: mesh-injection-patch.yaml
